const products=[{id:1,name:"JHOKA SNACK CLÁSICO",desc:"Chifle crocante de plátano",price:6,imageBase:"images/chifle-clasico"},{id:2,name:"JHOKA SNACK ESPECIAL",desc:"Sabor intenso y extra crocante",price:7,imageBase:"images/chifle-especial"},{id:3,name:"JHOKA SNACK PICANTE",desc:"El toque que eleva el sabor",price:7.5,imageBase:"images/chifle-picante"}];
const imageExtensions=["png","jpg","jpeg","webp"];
let cart=JSON.parse(localStorage.getItem("jhokaCart")||"[]");const $=s=>document.querySelector(s);
function findImage(base,callback){let i=0;function tryNext(){if(i>=imageExtensions.length){callback("");return}const src=base+"."+imageExtensions[i++],img=new Image();img.onload=()=>callback(src);img.onerror=tryNext;img.src=src}tryNext()}
function renderProducts(){productGrid.innerHTML=products.map(p=>`<article class="product"><div class="product-img" id="img-${p.id}"><span>Cargando foto…</span></div><div class="product-info"><h3>${p.name}</h3><p>${p.desc}</p><div class="product-row"><span class="price">S/ ${p.price.toFixed(2)}</span><button class="add" onclick="addToCart(${p.id})">+ AGREGAR</button></div></div></article>`).join("");products.forEach(p=>findImage(p.imageBase,src=>{const box=document.querySelector("#img-"+p.id);if(!box)return;box.innerHTML=src?`<img src="${src}" alt="${p.name}" loading="lazy">`:"<span>Sube la foto del producto</span>"}))}
function loadHero(){findImage("images/banner",src=>{const box=$("#heroPhoto");if(!box)return;box.innerHTML=src?`<img src="${src}" alt="JHOKA SNACK - Banner" loading="eager">`:"<span>Sube la foto banner</span>"})}
function addToCart(id){let x=cart.find(i=>i.id===id);x?x.qty++:cart.push({id,qty:1});save();openCart()}
function save(){localStorage.setItem("jhokaCart",JSON.stringify(cart));renderCart()}
function renderCart(){let count=cart.reduce((s,x)=>s+x.qty,0),total=0;cartCount.textContent=count;if(!cart.length){cartItems.innerHTML="";emptyCart.style.display="block"}else{emptyCart.style.display="none";cartItems.innerHTML=cart.map(x=>{let p=products.find(i=>i.id===x.id);total+=p.price*x.qty;return `<div class="cart-item"><div><strong>${p.name}</strong><br>S/ ${(p.price*x.qty).toFixed(2)}</div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${x.qty}</b><button onclick="changeQty(${p.id},1)">+</button></div></div>`}).join("")}cartTotal.textContent=total.toFixed(2)}
function changeQty(id,n){let x=cart.find(i=>i.id===id);if(!x)return;x.qty+=n;if(x.qty<=0)cart=cart.filter(i=>i.id!==id);save()}
function openCart(){cartEl.classList.add("open");overlay.classList.add("open")}function closeCart(){cartEl.classList.remove("open");overlay.classList.remove("open")}
function sendWhatsApp(){if(!cart.length){alert("Agrega al menos un producto.");return}let name=customerName.value.trim()||"Cliente",note=orderNote.value.trim();let lines=cart.map(x=>{let p=products.find(i=>i.id===x.id);return `• ${p.name} x${x.qty} — S/ ${(p.price*x.qty).toFixed(2)}`});let total=cart.reduce((s,x)=>s+products.find(i=>i.id===x.id).price*x.qty,0);let msg=`Hola JHOKA SNACK 👋\nQuiero hacer este pedido:\n\n${lines.join("\n")}\n\nTOTAL: S/ ${total.toFixed(2)}\nNombre: ${name}${note?"\nNota: "+note:""}`;window.open("https://wa.me/51938580402?text="+encodeURIComponent(msg),"_blank")}
const productGrid=$("#productGrid"),cartEl=$("#cart"),overlay=$("#overlay"),cartItems=$("#cartItems"),emptyCart=$("#emptyCart"),cartCount=$("#cartCount"),cartTotal=$("#cartTotal"),customerName=$("#customerName"),orderNote=$("#orderNote");
$("#openCart").onclick=openCart;$("#heroCart").onclick=openCart;$("#contactCart").onclick=openCart;$("#closeCart").onclick=closeCart;overlay.onclick=closeCart;$("#whatsappBtn").onclick=sendWhatsApp;renderProducts();loadHero();renderCart();